name: getting_started
description: Sample application for DNB's APIs.
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dnb: ^1.0.1
  dotenv: ^1.0.0

dev_dependencies:
  test: ^1.5.3