version: 2.1
commands:
  npm_install:
    description: "Install npm dependencies"
    steps:
      - restore_cache:
          key: v1-{{ checksum "nodejs/package-lock.json" }}

      - run:
          command: npm ci
          working_directory: nodejs

      - save_cache:
          key: v1-{{ checksum "nodejs/package-lock.json" }}
          paths:
            - "nodejs/node_modules"

  pub_get:
    description: "Install pub dependencies"
    steps:
      - restore_cache:
          key: v1-{{ checksum "dart/pubspec.lock" }}
      - run:
          command: pub get
          working_directory: dart
      - save_cache:
          key: v1-{{ checksum "dart/pubspec.lock" }}
          paths:
            - "$HOME/.pub_cache"

jobs:
  npm:
    parameters:
      task:
        description: "npm task to run"
        type: string
    docker:
      - image: circleci/node
    steps:
      - checkout
      - npm_install
      - run:
          command: npm run <<parameters.task>>
          working_directory: nodejs

  pub:
    parameters:
      task:
        description: "pub task to run"
        type: string
    docker:
      - image: google/dart
    steps:
      - checkout
      - pub_get
      - run:
          command: pub run <<parameters.task>>
          working_directory: dart

  dartanalyzer:
    docker:
      - image: google/dart
    steps:
      - checkout
      - pub_get
      - run:
          command: dartanalyzer lib/main.dart
          working_directory: dart
      - run:
          command: dartanalyzer test/integration_tests.dart
          working_directory: dart


workflows:
  version: 2
  nodejs:
    jobs:
      - npm:
          name: nodejs-example lint
          task: lint
      - npm:
          name: nodejs-example test
          task: test

  dart:
    jobs:
      - dartanalyzer:
          name: dart-example analyze
      - pub:
          name: dart-example test
          task: test test/integration_tests.dart