version: 2.1
commands:
  npm_install:
    description: "Install npm dependencies"
    steps:
      - restore_cache:
          key: v1-{{ checksum "nodejs/package-lock.json" }}

      - run:
          command: npm ci
          working_directory: nodejs

      - save_cache:
          key: v1-{{ checksum "nodejs/package-lock.json" }}
          paths:
            - "nodejs/node_modules"

  pub_get:
    description: "Install pub dependencies"
    steps:
      - restore_cache:
          key: v1-{{ checksum "dart/pubspec.lock" }}
      - run:
          command: pub get
          working_directory: dart
      - save_cache:
          key: v1-{{ checksum "dart/pubspec.lock" }}
          paths:
            - "$HOME/.pub_cache"
  pipenv_install:
    description: "Install python dependencies"
    steps:
      - restore_cache:
          key: v2-{{ checksum "python/Pipfile.lock" }}

      - run: pip install pipenv
      - run:
          command: pipenv install --dev
          working_directory: python

      - save_cache:
          key: v2-{{ checksum "python/Pipfile.lock" }}
          paths:
            - ~/.local/share/virtualenvs/venv

  maven_install:
    description: "Install maven dependencies"
    steps:
      - restore_cache:
          key: v1-{{ checksum "java/pom.xml" }}

      - run:
          command: mvn dependency:go-offline
          working_directory: java

      - save_cache:
          paths:
            - ~/.m2
          key: v1-{{ checksum "java/pom.xml" }}

jobs:
  npm:
    parameters:
      task:
        description: "npm task to run"
        type: string
    docker:
      - image: circleci/node
    steps:
      - checkout
      - npm_install
      - run:
          command: npm <<parameters.task>>
          working_directory: nodejs

  dart:
    parameters:
      tool:
        description: "tool to run"
        type: string
      task:
        description: "task to run"
        type: string
    docker:
      - image: google/dart
    steps:
      - checkout
      - pub_get
      - run:
          command: <<parameters.tool>> <<parameters.task>>
          working_directory: dart

  dartanalyzer:
    docker:
      - image: google/dart
    steps:
      - checkout
      - run:
          command: dartanalyzer lib/main.dart
          working_directory: dart
      - run:
          command: dartanalyzer test/integration_tests.dart
          working_directory: dart
  python:
    parameters:
      task:
        description: "python task to run"
        type: string
    docker:
      - image: circleci/python
    steps:
      - checkout
      - pipenv_install
      - run:
          command: pipenv run <<parameters.task>>
          working_directory: python

  maven:
    parameters:
      task:
        description: "maven task to run"
        type: string
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - maven_install
      - run:
          command: mvn <<parameters.task>>
          working_directory: java


workflows:
  version: 2
  nodejs:
    jobs:
      - npm:
          name: nodejs-example security audit
          task: audit
      - npm:
          name: nodejs-example lint
          task: run lint
      - npm:
          name: nodejs-example test
          task: test

  dart:
    jobs:
      - dart:
          name: dart-example analyze
          tool: dartanalyzer
          task: lib/main.dart
      - dart:
          name: dart-example test
          tool: pub run
          task: test test/integration_tests.dart
  python:
    jobs:
      - python:
          name: python-example format
          task: black --check .
      - python:
          name: python-example flake8
          task: flake8
      - python:
          name: python-example test
          task: pytest
  java:
    jobs:
      - maven:
          name: java-example compile
          task: compile
